import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { mcpError, mcpSuccess } from "@cmsmcp/shared";
import type { ShopifyClient } from "../api/client.js";
import { ListCustomCollectionsSchema, GetCustomCollectionSchema, CreateCustomCollectionSchema, UpdateCustomCollectionSchema, DeleteCustomCollectionSchema, ListSmartCollectionsSchema, GetSmartCollectionSchema, CreateSmartCollectionSchema, UpdateSmartCollectionSchema, DeleteSmartCollectionSchema, ListCollectsSchema, CreateCollectSchema, DeleteCollectSchema } from "../schemas/index.js";

export function registerCollectionTools(server: McpServer, client: ShopifyClient): void {
  // Custom Collections
  server.tool("shopify_list_custom_collections", "List custom (manual) collections.", ListCustomCollectionsSchema.shape, async (p) => { try { return mcpSuccess(await client.list("custom_collections", ListCustomCollectionsSchema.parse(p) as Record<string, string | number | boolean | undefined>)); } catch(e) { return mcpError(e, "shopify_list_custom_collections"); } });
  server.tool("shopify_get_custom_collection", "Get a custom collection.", GetCustomCollectionSchema.shape, async (p) => { try { return mcpSuccess(await client.get(`custom_collections/${GetCustomCollectionSchema.parse(p).id}`)); } catch(e) { return mcpError(e, "shopify_get_custom_collection"); } });
  server.tool("shopify_create_custom_collection", "Create a manual collection.", CreateCustomCollectionSchema.shape, async (p) => { try { return mcpSuccess(await client.post("custom_collections", { custom_collection: CreateCustomCollectionSchema.parse(p) })); } catch(e) { return mcpError(e, "shopify_create_custom_collection"); } });
  server.tool("shopify_update_custom_collection", "Update a custom collection.", UpdateCustomCollectionSchema.shape, async (p) => { try { const { id, ...d } = UpdateCustomCollectionSchema.parse(p); return mcpSuccess(await client.put(`custom_collections/${id}`, { custom_collection: d })); } catch(e) { return mcpError(e, "shopify_update_custom_collection"); } });
  server.tool("shopify_delete_custom_collection", "Delete a custom collection.", DeleteCustomCollectionSchema.shape, async (p) => { try { await client.del(`custom_collections/${DeleteCustomCollectionSchema.parse(p).id}`); return mcpSuccess({ message: "Collection deleted" }); } catch(e) { return mcpError(e, "shopify_delete_custom_collection"); } });
  // Smart Collections
  server.tool("shopify_list_smart_collections", "List smart (automated) collections.", ListSmartCollectionsSchema.shape, async (p) => { try { return mcpSuccess(await client.list("smart_collections", ListSmartCollectionsSchema.parse(p) as Record<string, string | number | boolean | undefined>)); } catch(e) { return mcpError(e, "shopify_list_smart_collections"); } });
  server.tool("shopify_get_smart_collection", "Get a smart collection with rules.", GetSmartCollectionSchema.shape, async (p) => { try { return mcpSuccess(await client.get(`smart_collections/${GetSmartCollectionSchema.parse(p).id}`)); } catch(e) { return mcpError(e, "shopify_get_smart_collection"); } });
  server.tool("shopify_create_smart_collection", "Create an automated collection with rules.", CreateSmartCollectionSchema.shape, async (p) => { try { return mcpSuccess(await client.post("smart_collections", { smart_collection: CreateSmartCollectionSchema.parse(p) })); } catch(e) { return mcpError(e, "shopify_create_smart_collection"); } });
  server.tool("shopify_update_smart_collection", "Update a smart collection or its rules.", UpdateSmartCollectionSchema.shape, async (p) => { try { const { id, ...d } = UpdateSmartCollectionSchema.parse(p); return mcpSuccess(await client.put(`smart_collections/${id}`, { smart_collection: d })); } catch(e) { return mcpError(e, "shopify_update_smart_collection"); } });
  server.tool("shopify_delete_smart_collection", "Delete a smart collection.", DeleteSmartCollectionSchema.shape, async (p) => { try { await client.del(`smart_collections/${DeleteSmartCollectionSchema.parse(p).id}`); return mcpSuccess({ message: "Smart collection deleted" }); } catch(e) { return mcpError(e, "shopify_delete_smart_collection"); } });
  // Collects
  server.tool("shopify_list_collects", "List product-collection relationships.", ListCollectsSchema.shape, async (p) => { try { return mcpSuccess(await client.list("collects", ListCollectsSchema.parse(p) as Record<string, string | number | boolean | undefined>)); } catch(e) { return mcpError(e, "shopify_list_collects"); } });
  server.tool("shopify_create_collect", "Add a product to a collection.", CreateCollectSchema.shape, async (p) => { try { return mcpSuccess(await client.post("collects", { collect: CreateCollectSchema.parse(p) })); } catch(e) { return mcpError(e, "shopify_create_collect"); } });
  server.tool("shopify_delete_collect", "Remove a product from a collection.", DeleteCollectSchema.shape, async (p) => { try { await client.del(`collects/${DeleteCollectSchema.parse(p).id}`); return mcpSuccess({ message: "Collect deleted" }); } catch(e) { return mcpError(e, "shopify_delete_collect"); } });
}
