import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { mcpError, mcpSuccess } from "@cmsmcp/shared";
import type { ShopifyClient } from "../api/client.js";
import { ListCustomersSchema, GetCustomerSchema, CountCustomersSchema, SearchCustomersSchema, CreateCustomerSchema, UpdateCustomerSchema, DeleteCustomerSchema, ListCustomerAddressesSchema, GetCustomerAddressSchema, CreateCustomerAddressSchema, UpdateCustomerAddressSchema, DeleteCustomerAddressSchema, SetDefaultAddressSchema } from "../schemas/index.js";

export function registerCustomerTools(server: McpServer, client: ShopifyClient): void {
  server.tool("shopify_list_customers", "List customers.", ListCustomersSchema.shape, async (p) => { try { return mcpSuccess(await client.list("customers", ListCustomersSchema.parse(p) as Record<string, string | number | boolean | undefined>)); } catch(e) { return mcpError(e, "shopify_list_customers"); } });
  server.tool("shopify_get_customer", "Get customer details.", GetCustomerSchema.shape, async (p) => { try { return mcpSuccess(await client.get(`customers/${GetCustomerSchema.parse(p).id}`)); } catch(e) { return mcpError(e, "shopify_get_customer"); } });
  server.tool("shopify_count_customers", "Count customers.", CountCustomersSchema.shape, async () => { try { return mcpSuccess(await client.get("customers/count")); } catch(e) { return mcpError(e, "shopify_count_customers"); } });
  server.tool("shopify_search_customers", "Search customers by name, email, etc.", SearchCustomersSchema.shape, async (p) => { try { const { query, ...q } = SearchCustomersSchema.parse(p); return mcpSuccess(await client.get("customers/search", { query, ...q } as Record<string, string | number | boolean | undefined>)); } catch(e) { return mcpError(e, "shopify_search_customers"); } });
  server.tool("shopify_create_customer", "Create a new customer.", CreateCustomerSchema.shape, async (p) => { try { return mcpSuccess(await client.post("customers", { customer: CreateCustomerSchema.parse(p) })); } catch(e) { return mcpError(e, "shopify_create_customer"); } });
  server.tool("shopify_update_customer", "Update customer info.", UpdateCustomerSchema.shape, async (p) => { try { const { id, ...d } = UpdateCustomerSchema.parse(p); return mcpSuccess(await client.put(`customers/${id}`, { customer: d })); } catch(e) { return mcpError(e, "shopify_update_customer"); } });
  server.tool("shopify_delete_customer", "Delete a customer.", DeleteCustomerSchema.shape, async (p) => { try { await client.del(`customers/${DeleteCustomerSchema.parse(p).id}`); return mcpSuccess({ message: "Customer deleted" }); } catch(e) { return mcpError(e, "shopify_delete_customer"); } });

  // Addresses
  server.tool("shopify_list_customer_addresses", "List customer addresses.", ListCustomerAddressesSchema.shape, async (p) => { try { const { customer_id, ...q } = ListCustomerAddressesSchema.parse(p); return mcpSuccess(await client.list(`customers/${customer_id}/addresses`, q as Record<string, string | number | boolean | undefined>)); } catch(e) { return mcpError(e, "shopify_list_customer_addresses"); } });
  server.tool("shopify_get_customer_address", "Get a customer address.", GetCustomerAddressSchema.shape, async (p) => { try { const { customer_id, address_id } = GetCustomerAddressSchema.parse(p); return mcpSuccess(await client.get(`customers/${customer_id}/addresses/${address_id}`)); } catch(e) { return mcpError(e, "shopify_get_customer_address"); } });
  server.tool("shopify_create_customer_address", "Add a new address for a customer.", CreateCustomerAddressSchema.shape, async (p) => { try { const { customer_id, ...d } = CreateCustomerAddressSchema.parse(p); return mcpSuccess(await client.post(`customers/${customer_id}/addresses`, { address: d })); } catch(e) { return mcpError(e, "shopify_create_customer_address"); } });
  server.tool("shopify_update_customer_address", "Update a customer address.", UpdateCustomerAddressSchema.shape, async (p) => { try { const { customer_id, address_id, ...d } = UpdateCustomerAddressSchema.parse(p); return mcpSuccess(await client.put(`customers/${customer_id}/addresses/${address_id}`, { address: d })); } catch(e) { return mcpError(e, "shopify_update_customer_address"); } });
  server.tool("shopify_delete_customer_address", "Delete a customer address.", DeleteCustomerAddressSchema.shape, async (p) => { try { const { customer_id, address_id } = DeleteCustomerAddressSchema.parse(p); await client.del(`customers/${customer_id}/addresses/${address_id}`); return mcpSuccess({ message: "Address deleted" }); } catch(e) { return mcpError(e, "shopify_delete_customer_address"); } });
  server.tool("shopify_set_default_address", "Set a customer's default address.", SetDefaultAddressSchema.shape, async (p) => { try { const { customer_id, address_id } = SetDefaultAddressSchema.parse(p); return mcpSuccess(await client.put(`customers/${customer_id}/addresses/${address_id}/default`, {})); } catch(e) { return mcpError(e, "shopify_set_default_address"); } });
}
