import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { mcpError, mcpSuccess } from "@cmsmcp/shared";
import type { ShopifyClient } from "../api/client.js";
import { ListOrdersSchema, GetOrderSchema, CountOrdersSchema, CreateOrderSchema, UpdateOrderSchema, CloseOrderSchema, CancelOrderSchema, ListDraftOrdersSchema, GetDraftOrderSchema, CreateDraftOrderSchema, UpdateDraftOrderSchema, DeleteDraftOrderSchema, CompleteDraftOrderSchema, SendDraftOrderInvoiceSchema, ListTransactionsSchema, GetTransactionSchema, CountTransactionsSchema, CreateTransactionSchema, ListRefundsSchema, GetRefundSchema, CreateRefundSchema, CalculateRefundSchema, ListFulfillmentsSchema, GetFulfillmentSchema, CountFulfillmentsSchema, CreateFulfillmentSchema, UpdateFulfillmentSchema, CancelFulfillmentSchema } from "../schemas/index.js";

export function registerOrderTools(server: McpServer, client: ShopifyClient): void {
  // Orders
  server.tool("shopify_list_orders", "List orders with status, financial, and fulfillment filters.", ListOrdersSchema.shape, async (p) => { try { return mcpSuccess(await client.list("orders", ListOrdersSchema.parse(p) as Record<string, string | number | boolean | undefined>)); } catch(e) { return mcpError(e, "shopify_list_orders"); } });
  server.tool("shopify_get_order", "Get full order details with line items.", GetOrderSchema.shape, async (p) => { try { return mcpSuccess(await client.get(`orders/${GetOrderSchema.parse(p).id}`)); } catch(e) { return mcpError(e, "shopify_get_order"); } });
  server.tool("shopify_count_orders", "Count orders.", CountOrdersSchema.shape, async (p) => { try { return mcpSuccess(await client.get("orders/count", CountOrdersSchema.parse(p) as Record<string, string | number | boolean | undefined>)); } catch(e) { return mcpError(e, "shopify_count_orders"); } });
  server.tool("shopify_create_order", "Create a new order with line items.", CreateOrderSchema.shape, async (p) => { try { return mcpSuccess(await client.post("orders", { order: CreateOrderSchema.parse(p) })); } catch(e) { return mcpError(e, "shopify_create_order"); } });
  server.tool("shopify_update_order", "Update order notes, tags, or shipping address.", UpdateOrderSchema.shape, async (p) => { try { const { id, ...d } = UpdateOrderSchema.parse(p); return mcpSuccess(await client.put(`orders/${id}`, { order: d })); } catch(e) { return mcpError(e, "shopify_update_order"); } });
  server.tool("shopify_close_order", "Close an order.", CloseOrderSchema.shape, async (p) => { try { return mcpSuccess(await client.post(`orders/${CloseOrderSchema.parse(p).id}/close`)); } catch(e) { return mcpError(e, "shopify_close_order"); } });
  server.tool("shopify_cancel_order", "Cancel an order with optional reason, email, and restock.", CancelOrderSchema.shape, async (p) => { try { const { id, ...d } = CancelOrderSchema.parse(p); return mcpSuccess(await client.post(`orders/${id}/cancel`, d)); } catch(e) { return mcpError(e, "shopify_cancel_order"); } });

  // Draft Orders
  server.tool("shopify_list_draft_orders", "List draft orders.", ListDraftOrdersSchema.shape, async (p) => { try { return mcpSuccess(await client.list("draft_orders", ListDraftOrdersSchema.parse(p) as Record<string, string | number | boolean | undefined>)); } catch(e) { return mcpError(e, "shopify_list_draft_orders"); } });
  server.tool("shopify_get_draft_order", "Get a draft order.", GetDraftOrderSchema.shape, async (p) => { try { return mcpSuccess(await client.get(`draft_orders/${GetDraftOrderSchema.parse(p).id}`)); } catch(e) { return mcpError(e, "shopify_get_draft_order"); } });
  server.tool("shopify_create_draft_order", "Create a draft order.", CreateDraftOrderSchema.shape, async (p) => { try { return mcpSuccess(await client.post("draft_orders", { draft_order: CreateDraftOrderSchema.parse(p) })); } catch(e) { return mcpError(e, "shopify_create_draft_order"); } });
  server.tool("shopify_update_draft_order", "Update a draft order.", UpdateDraftOrderSchema.shape, async (p) => { try { const { id, ...d } = UpdateDraftOrderSchema.parse(p); return mcpSuccess(await client.put(`draft_orders/${id}`, { draft_order: d })); } catch(e) { return mcpError(e, "shopify_update_draft_order"); } });
  server.tool("shopify_delete_draft_order", "Delete a draft order.", DeleteDraftOrderSchema.shape, async (p) => { try { await client.del(`draft_orders/${DeleteDraftOrderSchema.parse(p).id}`); return mcpSuccess({ message: "Draft order deleted" }); } catch(e) { return mcpError(e, "shopify_delete_draft_order"); } });
  server.tool("shopify_complete_draft_order", "Convert draft order to a real order.", CompleteDraftOrderSchema.shape, async (p) => { try { const { id, ...d } = CompleteDraftOrderSchema.parse(p); return mcpSuccess(await client.put(`draft_orders/${id}/complete`, d)); } catch(e) { return mcpError(e, "shopify_complete_draft_order"); } });
  server.tool("shopify_send_draft_invoice", "Email a draft order invoice to the customer.", SendDraftOrderInvoiceSchema.shape, async (p) => { try { const { id, ...d } = SendDraftOrderInvoiceSchema.parse(p); return mcpSuccess(await client.post(`draft_orders/${id}/send_invoice`, { draft_order_invoice: d })); } catch(e) { return mcpError(e, "shopify_send_draft_invoice"); } });

  // Transactions
  server.tool("shopify_list_transactions", "List transactions for an order.", ListTransactionsSchema.shape, async (p) => { try { return mcpSuccess(await client.get(`orders/${ListTransactionsSchema.parse(p).order_id}/transactions`)); } catch(e) { return mcpError(e, "shopify_list_transactions"); } });
  server.tool("shopify_get_transaction", "Get a specific transaction.", GetTransactionSchema.shape, async (p) => { try { const { order_id, transaction_id } = GetTransactionSchema.parse(p); return mcpSuccess(await client.get(`orders/${order_id}/transactions/${transaction_id}`)); } catch(e) { return mcpError(e, "shopify_get_transaction"); } });
  server.tool("shopify_count_transactions", "Count transactions for an order.", CountTransactionsSchema.shape, async (p) => { try { return mcpSuccess(await client.get(`orders/${CountTransactionsSchema.parse(p).order_id}/transactions/count`)); } catch(e) { return mcpError(e, "shopify_count_transactions"); } });
  server.tool("shopify_create_transaction", "Create a transaction (capture, void, refund) on an order.", CreateTransactionSchema.shape, async (p) => { try { const { order_id, ...d } = CreateTransactionSchema.parse(p); return mcpSuccess(await client.post(`orders/${order_id}/transactions`, { transaction: d })); } catch(e) { return mcpError(e, "shopify_create_transaction"); } });

  // Refunds
  server.tool("shopify_list_refunds", "List refunds for an order.", ListRefundsSchema.shape, async (p) => { try { return mcpSuccess(await client.get(`orders/${ListRefundsSchema.parse(p).order_id}/refunds`)); } catch(e) { return mcpError(e, "shopify_list_refunds"); } });
  server.tool("shopify_get_refund", "Get refund details.", GetRefundSchema.shape, async (p) => { try { const { order_id, refund_id } = GetRefundSchema.parse(p); return mcpSuccess(await client.get(`orders/${order_id}/refunds/${refund_id}`)); } catch(e) { return mcpError(e, "shopify_get_refund"); } });
  server.tool("shopify_create_refund", "Create a refund with optional line items and shipping.", CreateRefundSchema.shape, async (p) => { try { const { order_id, ...d } = CreateRefundSchema.parse(p); return mcpSuccess(await client.post(`orders/${order_id}/refunds`, { refund: d })); } catch(e) { return mcpError(e, "shopify_create_refund"); } });
  server.tool("shopify_calculate_refund", "Calculate a refund before creating it.", CalculateRefundSchema.shape, async (p) => { try { const { order_id, ...d } = CalculateRefundSchema.parse(p); return mcpSuccess(await client.post(`orders/${order_id}/refunds/calculate`, { refund: d })); } catch(e) { return mcpError(e, "shopify_calculate_refund"); } });

  // Fulfillments
  server.tool("shopify_list_fulfillments", "List fulfillments for an order.", ListFulfillmentsSchema.shape, async (p) => { try { const { order_id, ...q } = ListFulfillmentsSchema.parse(p); return mcpSuccess(await client.list(`orders/${order_id}/fulfillments`, q as Record<string, string | number | boolean | undefined>)); } catch(e) { return mcpError(e, "shopify_list_fulfillments"); } });
  server.tool("shopify_get_fulfillment", "Get fulfillment details.", GetFulfillmentSchema.shape, async (p) => { try { const { order_id, fulfillment_id } = GetFulfillmentSchema.parse(p); return mcpSuccess(await client.get(`orders/${order_id}/fulfillments/${fulfillment_id}`)); } catch(e) { return mcpError(e, "shopify_get_fulfillment"); } });
  server.tool("shopify_count_fulfillments", "Count fulfillments for an order.", CountFulfillmentsSchema.shape, async (p) => { try { return mcpSuccess(await client.get(`orders/${CountFulfillmentsSchema.parse(p).order_id}/fulfillments/count`)); } catch(e) { return mcpError(e, "shopify_count_fulfillments"); } });
  server.tool("shopify_create_fulfillment", "Fulfill an order with tracking info.", CreateFulfillmentSchema.shape, async (p) => { try { const { order_id, ...d } = CreateFulfillmentSchema.parse(p); return mcpSuccess(await client.post(`orders/${order_id}/fulfillments`, { fulfillment: d })); } catch(e) { return mcpError(e, "shopify_create_fulfillment"); } });
  server.tool("shopify_update_fulfillment", "Update fulfillment tracking.", UpdateFulfillmentSchema.shape, async (p) => { try { const { order_id, fulfillment_id, ...d } = UpdateFulfillmentSchema.parse(p); return mcpSuccess(await client.put(`orders/${order_id}/fulfillments/${fulfillment_id}`, { fulfillment: d })); } catch(e) { return mcpError(e, "shopify_update_fulfillment"); } });
  server.tool("shopify_cancel_fulfillment", "Cancel a fulfillment.", CancelFulfillmentSchema.shape, async (p) => { try { const { order_id, fulfillment_id } = CancelFulfillmentSchema.parse(p); return mcpSuccess(await client.post(`orders/${order_id}/fulfillments/${fulfillment_id}/cancel`)); } catch(e) { return mcpError(e, "shopify_cancel_fulfillment"); } });
}
