import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { mcpError, mcpSuccess } from "@cmsmcp/shared";
import type { ShopifyClient } from "../api/client.js";
import { ListProductsSchema, GetProductSchema, CountProductsSchema, CreateProductSchema, UpdateProductSchema, DeleteProductSchema, ListVariantsSchema, GetVariantSchema, CountVariantsSchema, CreateVariantSchema, UpdateVariantSchema, DeleteVariantSchema, ListProductImagesSchema, GetProductImageSchema, CountProductImagesSchema, CreateProductImageSchema, UpdateProductImageSchema, DeleteProductImageSchema } from "../schemas/index.js";

export function registerProductTools(server: McpServer, client: ShopifyClient): void {
  // Products
  server.tool("shopify_list_products", "List Shopify products with filters (type, vendor, status, collection).", ListProductsSchema.shape, async (p) => { try { const v = ListProductsSchema.parse(p); return mcpSuccess(await client.list("products", v as Record<string, string | number | boolean | undefined>)); } catch(e) { return mcpError(e, "shopify_list_products"); } });
  server.tool("shopify_get_product", "Get a product with all variants and images.", GetProductSchema.shape, async (p) => { try { return mcpSuccess(await client.get(`products/${GetProductSchema.parse(p).id}`)); } catch(e) { return mcpError(e, "shopify_get_product"); } });
  server.tool("shopify_count_products", "Count products matching filters.", CountProductsSchema.shape, async (p) => { try { return mcpSuccess(await client.get("products/count", CountProductsSchema.parse(p) as Record<string, string | number | boolean | undefined>)); } catch(e) { return mcpError(e, "shopify_count_products"); } });
  server.tool("shopify_create_product", "Create a new Shopify product with variants and images.", CreateProductSchema.shape, async (p) => { try { const v = CreateProductSchema.parse(p); const r = await client.post<Record<string, unknown>>("products", { product: v }); return mcpSuccess(r); } catch(e) { return mcpError(e, "shopify_create_product"); } });
  server.tool("shopify_update_product", "Update a product's title, description, tags, status, etc.", UpdateProductSchema.shape, async (p) => { try { const { id, ...d } = UpdateProductSchema.parse(p); return mcpSuccess(await client.put(`products/${id}`, { product: d })); } catch(e) { return mcpError(e, "shopify_update_product"); } });
  server.tool("shopify_delete_product", "Delete a product.", DeleteProductSchema.shape, async (p) => { try { await client.del(`products/${DeleteProductSchema.parse(p).id}`); return mcpSuccess({ message: "Product deleted" }); } catch(e) { return mcpError(e, "shopify_delete_product"); } });

  // Variants
  server.tool("shopify_list_variants", "List variants of a product.", ListVariantsSchema.shape, async (p) => { try { const { product_id, ...q } = ListVariantsSchema.parse(p); return mcpSuccess(await client.list(`products/${product_id}/variants`, q as Record<string, string | number | boolean | undefined>)); } catch(e) { return mcpError(e, "shopify_list_variants"); } });
  server.tool("shopify_get_variant", "Get a specific variant.", GetVariantSchema.shape, async (p) => { try { return mcpSuccess(await client.get(`variants/${GetVariantSchema.parse(p).variant_id}`)); } catch(e) { return mcpError(e, "shopify_get_variant"); } });
  server.tool("shopify_count_variants", "Count variants of a product.", CountVariantsSchema.shape, async (p) => { try { return mcpSuccess(await client.get(`products/${CountVariantsSchema.parse(p).product_id}/variants/count`)); } catch(e) { return mcpError(e, "shopify_count_variants"); } });
  server.tool("shopify_create_variant", "Create a product variant with price, SKU, options.", CreateVariantSchema.shape, async (p) => { try { const { product_id, ...d } = CreateVariantSchema.parse(p); return mcpSuccess(await client.post(`products/${product_id}/variants`, { variant: d })); } catch(e) { return mcpError(e, "shopify_create_variant"); } });
  server.tool("shopify_update_variant", "Update a variant's price, SKU, inventory, etc.", UpdateVariantSchema.shape, async (p) => { try { const { variant_id, ...d } = UpdateVariantSchema.parse(p); return mcpSuccess(await client.put(`variants/${variant_id}`, { variant: d })); } catch(e) { return mcpError(e, "shopify_update_variant"); } });
  server.tool("shopify_delete_variant", "Delete a product variant.", DeleteVariantSchema.shape, async (p) => { try { const { product_id, variant_id } = DeleteVariantSchema.parse(p); await client.del(`products/${product_id}/variants/${variant_id}`); return mcpSuccess({ message: "Variant deleted" }); } catch(e) { return mcpError(e, "shopify_delete_variant"); } });

  // Images
  server.tool("shopify_list_product_images", "List images for a product.", ListProductImagesSchema.shape, async (p) => { try { return mcpSuccess(await client.get(`products/${ListProductImagesSchema.parse(p).product_id}/images`)); } catch(e) { return mcpError(e, "shopify_list_product_images"); } });
  server.tool("shopify_get_product_image", "Get a specific product image.", GetProductImageSchema.shape, async (p) => { try { const { product_id, image_id } = GetProductImageSchema.parse(p); return mcpSuccess(await client.get(`products/${product_id}/images/${image_id}`)); } catch(e) { return mcpError(e, "shopify_get_product_image"); } });
  server.tool("shopify_count_product_images", "Count images for a product.", CountProductImagesSchema.shape, async (p) => { try { return mcpSuccess(await client.get(`products/${CountProductImagesSchema.parse(p).product_id}/images/count`)); } catch(e) { return mcpError(e, "shopify_count_product_images"); } });
  server.tool("shopify_create_product_image", "Add an image to a product from URL or base64.", CreateProductImageSchema.shape, async (p) => { try { const { product_id, ...d } = CreateProductImageSchema.parse(p); return mcpSuccess(await client.post(`products/${product_id}/images`, { image: d })); } catch(e) { return mcpError(e, "shopify_create_product_image"); } });
  server.tool("shopify_update_product_image", "Update image alt text, position, or variant associations.", UpdateProductImageSchema.shape, async (p) => { try { const { product_id, image_id, ...d } = UpdateProductImageSchema.parse(p); return mcpSuccess(await client.put(`products/${product_id}/images/${image_id}`, { image: d })); } catch(e) { return mcpError(e, "shopify_update_product_image"); } });
  server.tool("shopify_delete_product_image", "Delete a product image.", DeleteProductImageSchema.shape, async (p) => { try { const { product_id, image_id } = DeleteProductImageSchema.parse(p); await client.del(`products/${product_id}/images/${image_id}`); return mcpSuccess({ message: "Image deleted" }); } catch(e) { return mcpError(e, "shopify_delete_product_image"); } });
}
