import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { mcpError, mcpSuccess } from "@cmsmcp/shared";
import type { ShopifyClient } from "../api/client.js";
import { ListThemesSchema, GetThemeSchema, ListAssetsSchema, GetAssetSchema, CreateOrUpdateAssetSchema, DeleteAssetSchema, GetShopSchema, ListPoliciesSchema, ListCurrenciesSchema, ListEventsSchema, GetEventSchema, CountEventsSchema, ListCountriesSchema, GetCountrySchema, ListPriceRulesSchema, GetPriceRuleSchema, CreatePriceRuleSchema, UpdatePriceRuleSchema, DeletePriceRuleSchema, ListDiscountCodesSchema, GetDiscountCodeSchema, CreateDiscountCodeSchema, UpdateDiscountCodeSchema, DeleteDiscountCodeSchema, ListGiftCardsSchema, GetGiftCardSchema, CountGiftCardsSchema, CreateGiftCardSchema, UpdateGiftCardSchema, SearchGiftCardsSchema, ListMetafieldsSchema, GetMetafieldSchema, CreateMetafieldSchema, UpdateMetafieldSchema, DeleteMetafieldSchema, ListWebhooksSchema, GetWebhookSchema, CountWebhooksSchema, CreateWebhookSchema, UpdateWebhookSchema, DeleteWebhookSchema } from "../schemas/index.js";

export function registerStoreTools(server: McpServer, client: ShopifyClient): void {
  // Themes & Assets
  server.tool("shopify_list_themes", "List installed themes.", ListThemesSchema.shape, async () => { try { return mcpSuccess(await client.get("themes")); } catch(e) { return mcpError(e, "shopify_list_themes"); } });
  server.tool("shopify_get_theme", "Get theme details.", GetThemeSchema.shape, async (p) => { try { return mcpSuccess(await client.get(`themes/${GetThemeSchema.parse(p).id}`)); } catch(e) { return mcpError(e, "shopify_get_theme"); } });
  server.tool("shopify_list_assets", "List all files in a theme.", ListAssetsSchema.shape, async (p) => { try { return mcpSuccess(await client.get(`themes/${ListAssetsSchema.parse(p).theme_id}/assets`)); } catch(e) { return mcpError(e, "shopify_list_assets"); } });
  server.tool("shopify_get_asset", "Get a theme file's content.", GetAssetSchema.shape, async (p) => { try { const { theme_id, key } = GetAssetSchema.parse(p); return mcpSuccess(await client.get(`themes/${theme_id}/assets`, { "asset[key]": key })); } catch(e) { return mcpError(e, "shopify_get_asset"); } });
  server.tool("shopify_create_or_update_asset", "Create or update a theme file.", CreateOrUpdateAssetSchema.shape, async (p) => { try { const { theme_id, ...d } = CreateOrUpdateAssetSchema.parse(p); return mcpSuccess(await client.put(`themes/${theme_id}/assets`, { asset: d })); } catch(e) { return mcpError(e, "shopify_create_or_update_asset"); } });
  server.tool("shopify_delete_asset", "Delete a theme file.", DeleteAssetSchema.shape, async (p) => { try { const { theme_id, key } = DeleteAssetSchema.parse(p); await client.del(`themes/${theme_id}/assets`, { "asset[key]": key }); return mcpSuccess({ message: "Asset deleted" }); } catch(e) { return mcpError(e, "shopify_delete_asset"); } });

  // Shop & Store info
  server.tool("shopify_get_shop", "Get store details (name, domain, plan, currency, timezone).", GetShopSchema.shape, async () => { try { return mcpSuccess(await client.get("shop")); } catch(e) { return mcpError(e, "shopify_get_shop"); } });
  server.tool("shopify_list_policies", "List store policies (privacy, refund, TOS).", ListPoliciesSchema.shape, async () => { try { return mcpSuccess(await client.get("policies")); } catch(e) { return mcpError(e, "shopify_list_policies"); } });
  server.tool("shopify_list_currencies", "List enabled currencies.", ListCurrenciesSchema.shape, async () => { try { return mcpSuccess(await client.get("currencies")); } catch(e) { return mcpError(e, "shopify_list_currencies"); } });
  server.tool("shopify_list_countries", "List countries configured for shipping.", ListCountriesSchema.shape, async () => { try { return mcpSuccess(await client.get("countries")); } catch(e) { return mcpError(e, "shopify_list_countries"); } });
  server.tool("shopify_get_country", "Get country details with provinces.", GetCountrySchema.shape, async (p) => { try { return mcpSuccess(await client.get(`countries/${GetCountrySchema.parse(p).id}`)); } catch(e) { return mcpError(e, "shopify_get_country"); } });

  // Events
  server.tool("shopify_list_events", "List store events (audit log).", ListEventsSchema.shape, async (p) => { try { return mcpSuccess(await client.list("events", ListEventsSchema.parse(p) as Record<string, string | number | boolean | undefined>)); } catch(e) { return mcpError(e, "shopify_list_events"); } });
  server.tool("shopify_get_event", "Get an event.", GetEventSchema.shape, async (p) => { try { return mcpSuccess(await client.get(`events/${GetEventSchema.parse(p).id}`)); } catch(e) { return mcpError(e, "shopify_get_event"); } });
  server.tool("shopify_count_events", "Count events.", CountEventsSchema.shape, async () => { try { return mcpSuccess(await client.get("events/count")); } catch(e) { return mcpError(e, "shopify_count_events"); } });

  // Price Rules & Discount Codes
  server.tool("shopify_list_price_rules", "List price rules (discount definitions).", ListPriceRulesSchema.shape, async (p) => { try { return mcpSuccess(await client.list("price_rules", ListPriceRulesSchema.parse(p) as Record<string, string | number | boolean | undefined>)); } catch(e) { return mcpError(e, "shopify_list_price_rules"); } });
  server.tool("shopify_get_price_rule", "Get a price rule.", GetPriceRuleSchema.shape, async (p) => { try { return mcpSuccess(await client.get(`price_rules/${GetPriceRuleSchema.parse(p).id}`)); } catch(e) { return mcpError(e, "shopify_get_price_rule"); } });
  server.tool("shopify_create_price_rule", "Create a price rule (percentage or fixed discount).", CreatePriceRuleSchema.shape, async (p) => { try { return mcpSuccess(await client.post("price_rules", { price_rule: CreatePriceRuleSchema.parse(p) })); } catch(e) { return mcpError(e, "shopify_create_price_rule"); } });
  server.tool("shopify_update_price_rule", "Update a price rule.", UpdatePriceRuleSchema.shape, async (p) => { try { const { id, ...d } = UpdatePriceRuleSchema.parse(p); return mcpSuccess(await client.put(`price_rules/${id}`, { price_rule: d })); } catch(e) { return mcpError(e, "shopify_update_price_rule"); } });
  server.tool("shopify_delete_price_rule", "Delete a price rule.", DeletePriceRuleSchema.shape, async (p) => { try { await client.del(`price_rules/${DeletePriceRuleSchema.parse(p).id}`); return mcpSuccess({ message: "Price rule deleted" }); } catch(e) { return mcpError(e, "shopify_delete_price_rule"); } });
  server.tool("shopify_list_discount_codes", "List discount codes for a price rule.", ListDiscountCodesSchema.shape, async (p) => { try { return mcpSuccess(await client.get(`price_rules/${ListDiscountCodesSchema.parse(p).price_rule_id}/discount_codes`)); } catch(e) { return mcpError(e, "shopify_list_discount_codes"); } });
  server.tool("shopify_get_discount_code", "Get a discount code.", GetDiscountCodeSchema.shape, async (p) => { try { const { price_rule_id, discount_code_id } = GetDiscountCodeSchema.parse(p); return mcpSuccess(await client.get(`price_rules/${price_rule_id}/discount_codes/${discount_code_id}`)); } catch(e) { return mcpError(e, "shopify_get_discount_code"); } });
  server.tool("shopify_create_discount_code", "Create a discount code (e.g., SAVE20).", CreateDiscountCodeSchema.shape, async (p) => { try { const { price_rule_id, ...d } = CreateDiscountCodeSchema.parse(p); return mcpSuccess(await client.post(`price_rules/${price_rule_id}/discount_codes`, { discount_code: d })); } catch(e) { return mcpError(e, "shopify_create_discount_code"); } });
  server.tool("shopify_update_discount_code", "Update a discount code.", UpdateDiscountCodeSchema.shape, async (p) => { try { const { price_rule_id, discount_code_id, ...d } = UpdateDiscountCodeSchema.parse(p); return mcpSuccess(await client.put(`price_rules/${price_rule_id}/discount_codes/${discount_code_id}`, { discount_code: d })); } catch(e) { return mcpError(e, "shopify_update_discount_code"); } });
  server.tool("shopify_delete_discount_code", "Delete a discount code.", DeleteDiscountCodeSchema.shape, async (p) => { try { const { price_rule_id, discount_code_id } = DeleteDiscountCodeSchema.parse(p); await client.del(`price_rules/${price_rule_id}/discount_codes/${discount_code_id}`); return mcpSuccess({ message: "Discount code deleted" }); } catch(e) { return mcpError(e, "shopify_delete_discount_code"); } });

  // Gift Cards
  server.tool("shopify_list_gift_cards", "List gift cards.", ListGiftCardsSchema.shape, async (p) => { try { return mcpSuccess(await client.list("gift_cards", ListGiftCardsSchema.parse(p) as Record<string, string | number | boolean | undefined>)); } catch(e) { return mcpError(e, "shopify_list_gift_cards"); } });
  server.tool("shopify_get_gift_card", "Get a gift card.", GetGiftCardSchema.shape, async (p) => { try { return mcpSuccess(await client.get(`gift_cards/${GetGiftCardSchema.parse(p).id}`)); } catch(e) { return mcpError(e, "shopify_get_gift_card"); } });
  server.tool("shopify_count_gift_cards", "Count gift cards.", CountGiftCardsSchema.shape, async (p) => { try { return mcpSuccess(await client.get("gift_cards/count", CountGiftCardsSchema.parse(p) as Record<string, string | number | boolean | undefined>)); } catch(e) { return mcpError(e, "shopify_count_gift_cards"); } });
  server.tool("shopify_create_gift_card", "Create a gift card.", CreateGiftCardSchema.shape, async (p) => { try { return mcpSuccess(await client.post("gift_cards", { gift_card: CreateGiftCardSchema.parse(p) })); } catch(e) { return mcpError(e, "shopify_create_gift_card"); } });
  server.tool("shopify_update_gift_card", "Update a gift card.", UpdateGiftCardSchema.shape, async (p) => { try { const { id, ...d } = UpdateGiftCardSchema.parse(p); return mcpSuccess(await client.put(`gift_cards/${id}`, { gift_card: d })); } catch(e) { return mcpError(e, "shopify_update_gift_card"); } });
  server.tool("shopify_search_gift_cards", "Search gift cards.", SearchGiftCardsSchema.shape, async (p) => { try { return mcpSuccess(await client.get("gift_cards/search", SearchGiftCardsSchema.parse(p) as Record<string, string | number | boolean | undefined>)); } catch(e) { return mcpError(e, "shopify_search_gift_cards"); } });

  // Metafields
  server.tool("shopify_list_metafields", "List metafields for any resource (products, orders, shop, etc.).", ListMetafieldsSchema.shape, async (p) => { try { const { resource, resource_id, ...q } = ListMetafieldsSchema.parse(p); const path = resource_id ? `${resource}/${resource_id}/metafields` : "metafields"; return mcpSuccess(await client.get(path, q as Record<string, string | number | boolean | undefined>)); } catch(e) { return mcpError(e, "shopify_list_metafields"); } });
  server.tool("shopify_get_metafield", "Get a metafield.", GetMetafieldSchema.shape, async (p) => { try { return mcpSuccess(await client.get(`metafields/${GetMetafieldSchema.parse(p).id}`)); } catch(e) { return mcpError(e, "shopify_get_metafield"); } });
  server.tool("shopify_create_metafield", "Create a metafield on any resource.", CreateMetafieldSchema.shape, async (p) => { try { const { resource, resource_id, ...d } = CreateMetafieldSchema.parse(p); const path = resource_id ? `${resource}/${resource_id}/metafields` : "metafields"; return mcpSuccess(await client.post(path, { metafield: d })); } catch(e) { return mcpError(e, "shopify_create_metafield"); } });
  server.tool("shopify_update_metafield", "Update a metafield value.", UpdateMetafieldSchema.shape, async (p) => { try { const { id, ...d } = UpdateMetafieldSchema.parse(p); return mcpSuccess(await client.put(`metafields/${id}`, { metafield: d })); } catch(e) { return mcpError(e, "shopify_update_metafield"); } });
  server.tool("shopify_delete_metafield", "Delete a metafield.", DeleteMetafieldSchema.shape, async (p) => { try { await client.del(`metafields/${DeleteMetafieldSchema.parse(p).id}`); return mcpSuccess({ message: "Metafield deleted" }); } catch(e) { return mcpError(e, "shopify_delete_metafield"); } });

  // Webhooks
  server.tool("shopify_list_webhooks", "List webhooks.", ListWebhooksSchema.shape, async (p) => { try { return mcpSuccess(await client.list("webhooks", ListWebhooksSchema.parse(p) as Record<string, string | number | boolean | undefined>)); } catch(e) { return mcpError(e, "shopify_list_webhooks"); } });
  server.tool("shopify_get_webhook", "Get a webhook.", GetWebhookSchema.shape, async (p) => { try { return mcpSuccess(await client.get(`webhooks/${GetWebhookSchema.parse(p).id}`)); } catch(e) { return mcpError(e, "shopify_get_webhook"); } });
  server.tool("shopify_count_webhooks", "Count webhooks.", CountWebhooksSchema.shape, async (p) => { try { return mcpSuccess(await client.get("webhooks/count", CountWebhooksSchema.parse(p) as Record<string, string | number | boolean | undefined>)); } catch(e) { return mcpError(e, "shopify_count_webhooks"); } });
  server.tool("shopify_create_webhook", "Create a webhook (e.g., orders/create, products/update).", CreateWebhookSchema.shape, async (p) => { try { return mcpSuccess(await client.post("webhooks", { webhook: CreateWebhookSchema.parse(p) })); } catch(e) { return mcpError(e, "shopify_create_webhook"); } });
  server.tool("shopify_update_webhook", "Update a webhook.", UpdateWebhookSchema.shape, async (p) => { try { const { id, ...d } = UpdateWebhookSchema.parse(p); return mcpSuccess(await client.put(`webhooks/${id}`, { webhook: d })); } catch(e) { return mcpError(e, "shopify_update_webhook"); } });
  server.tool("shopify_delete_webhook", "Delete a webhook.", DeleteWebhookSchema.shape, async (p) => { try { await client.del(`webhooks/${DeleteWebhookSchema.parse(p).id}`); return mcpSuccess({ message: "Webhook deleted" }); } catch(e) { return mcpError(e, "shopify_delete_webhook"); } });
}
