import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { mcpError, mcpSuccess } from "@cmsmcp/shared";
import type { WpClient } from "../api/client.js";
import { ListMenusSchema, GetMenuSchema, CreateMenuSchema, UpdateMenuSchema, DeleteMenuSchema, ListMenuItemsSchema, GetMenuItemSchema, CreateMenuItemSchema, UpdateMenuItemSchema, DeleteMenuItemSchema, ListMenuLocationsSchema, GetMenuLocationSchema } from "../schemas/index.js";

export function registerMenuTools(server: McpServer, client: WpClient): void {
  server.tool("wp_list_menus", "List navigation menus.", ListMenusSchema.shape, async (p) => { try { const { page, per_page } = ListMenusSchema.parse(p); return mcpSuccess(await client.list("menus", {}, page, per_page)); } catch(e) { return mcpError(e, "wp_list_menus"); } });
  server.tool("wp_get_menu", "Get a menu by ID.", GetMenuSchema.shape, async (p) => { try { return mcpSuccess(await client.get(`menus/${GetMenuSchema.parse(p).id}`)); } catch(e) { return mcpError(e, "wp_get_menu"); } });
  server.tool("wp_create_menu", "Create a new navigation menu.", CreateMenuSchema.shape, async (p) => { try { const v = CreateMenuSchema.parse(p); const m = await client.post<Record<string, unknown>>("menus", v); return mcpSuccess({ id: m["id"], name: m["name"], message: `Menu '${m["name"]}' created` }); } catch(e) { return mcpError(e, "wp_create_menu"); } });
  server.tool("wp_update_menu", "Update a menu.", UpdateMenuSchema.shape, async (p) => { try { const { id, ...d } = UpdateMenuSchema.parse(p); await client.put(`menus/${id}`, d); return mcpSuccess({ message: `Menu ${id} updated` }); } catch(e) { return mcpError(e, "wp_update_menu"); } });
  server.tool("wp_delete_menu", "Delete a menu.", DeleteMenuSchema.shape, async (p) => { try { const { id, force } = DeleteMenuSchema.parse(p); await client.del(`menus/${id}`, { force }); return mcpSuccess({ message: `Menu ${id} deleted` }); } catch(e) { return mcpError(e, "wp_delete_menu"); } });
  server.tool("wp_list_menu_items", "List menu items, optionally filtered by menu ID.", ListMenuItemsSchema.shape, async (p) => { try { const { page, per_page, ...f } = ListMenuItemsSchema.parse(p); return mcpSuccess(await client.list("menu-items", f as Record<string, string | number | boolean | undefined>, page, per_page)); } catch(e) { return mcpError(e, "wp_list_menu_items"); } });
  server.tool("wp_create_menu_item", "Add an item to a navigation menu (page, post, custom URL, or taxonomy link).", CreateMenuItemSchema.shape, async (p) => { try { const v = CreateMenuItemSchema.parse(p); const m = await client.post<Record<string, unknown>>("menu-items", v); return mcpSuccess({ id: m["id"], message: "Menu item created" }); } catch(e) { return mcpError(e, "wp_create_menu_item"); } });
  server.tool("wp_update_menu_item", "Update a menu item's title, order, or parent.", UpdateMenuItemSchema.shape, async (p) => { try { const { id, ...d } = UpdateMenuItemSchema.parse(p); await client.put(`menu-items/${id}`, d); return mcpSuccess({ message: `Menu item ${id} updated` }); } catch(e) { return mcpError(e, "wp_update_menu_item"); } });
  server.tool("wp_delete_menu_item", "Delete a menu item.", DeleteMenuItemSchema.shape, async (p) => { try { const { id, force } = DeleteMenuItemSchema.parse(p); await client.del(`menu-items/${id}`, { force }); return mcpSuccess({ message: `Menu item ${id} deleted` }); } catch(e) { return mcpError(e, "wp_delete_menu_item"); } });
  server.tool("wp_get_menu_item", "Get a single menu item by ID.", GetMenuItemSchema.shape, async (p) => { try { return mcpSuccess(await client.get(`menu-items/${GetMenuItemSchema.parse(p).id}`)); } catch(e) { return mcpError(e, "wp_get_menu_item"); } });
  server.tool("wp_list_menu_locations", "List registered menu locations (header, footer, sidebar, etc.).", ListMenuLocationsSchema.shape, async () => { try { return mcpSuccess(await client.get("menu-locations")); } catch(e) { return mcpError(e, "wp_list_menu_locations"); } });
  server.tool("wp_get_menu_location", "Get a specific menu location and its assigned menu.", GetMenuLocationSchema.shape, async (p) => { try { return mcpSuccess(await client.get(`menu-locations/${GetMenuLocationSchema.parse(p).location}`)); } catch(e) { return mcpError(e, "wp_get_menu_location"); } });
}
