import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { mcpError, mcpSuccess } from "@cmsmcp/shared";
import type { WpClient } from "../api/client.js";
import {
  ListTemplatesSchema, GetTemplateSchema, CreateTemplateSchema, UpdateTemplateSchema, DeleteTemplateSchema,
  ListTemplatePartsSchema, GetTemplatePartSchema, CreateTemplatePartSchema, UpdateTemplatePartSchema, DeleteTemplatePartSchema,
  ListNavigationsSchema, GetNavigationSchema, CreateNavigationSchema, UpdateNavigationSchema, DeleteNavigationSchema,
  GetGlobalStylesSchema, UpdateGlobalStylesSchema, GetThemeGlobalStylesSchema, ListGlobalStyleVariationsSchema,
} from "../schemas/index.js";

export function registerSiteEditorTools(server: McpServer, client: WpClient): void {
  // Templates — full CRUD
  server.tool("wp_list_templates", "List block templates.", ListTemplatesSchema.shape, async (p) => { try { const { page, per_page } = ListTemplatesSchema.parse(p); return mcpSuccess(await client.list("templates", {}, page, per_page)); } catch(e) { return mcpError(e, "wp_list_templates"); } });
  server.tool("wp_get_template", "Get a block template by ID.", GetTemplateSchema.shape, async (p) => { try { return mcpSuccess(await client.get(`templates/${GetTemplateSchema.parse(p).id}`)); } catch(e) { return mcpError(e, "wp_get_template"); } });
  server.tool("wp_create_template", "Create a custom block template.", CreateTemplateSchema.shape, async (p) => { try { const v = CreateTemplateSchema.parse(p); const t = await client.post<Record<string, unknown>>("templates", v); return mcpSuccess({ id: t["id"], message: "Template created" }); } catch(e) { return mcpError(e, "wp_create_template"); } });
  server.tool("wp_update_template", "Update a block template's content or title.", UpdateTemplateSchema.shape, async (p) => { try { const { id, ...d } = UpdateTemplateSchema.parse(p); await client.put(`templates/${id}`, d); return mcpSuccess({ message: "Template updated" }); } catch(e) { return mcpError(e, "wp_update_template"); } });
  server.tool("wp_delete_template", "Delete a custom block template.", DeleteTemplateSchema.shape, async (p) => { try { const { id, force } = DeleteTemplateSchema.parse(p); await client.del(`templates/${id}`, { force }); return mcpSuccess({ message: "Template deleted" }); } catch(e) { return mcpError(e, "wp_delete_template"); } });
  // Template Parts — full CRUD
  server.tool("wp_list_template_parts", "List template parts (header, footer, sidebar areas).", ListTemplatePartsSchema.shape, async (p) => { try { const { page, per_page, ...f } = ListTemplatePartsSchema.parse(p); return mcpSuccess(await client.list("template-parts", f as Record<string, string | number | boolean | undefined>, page, per_page)); } catch(e) { return mcpError(e, "wp_list_template_parts"); } });
  server.tool("wp_get_template_part", "Get a template part by ID.", GetTemplatePartSchema.shape, async (p) => { try { return mcpSuccess(await client.get(`template-parts/${GetTemplatePartSchema.parse(p).id}`)); } catch(e) { return mcpError(e, "wp_get_template_part"); } });
  server.tool("wp_create_template_part", "Create a template part (header, footer, sidebar).", CreateTemplatePartSchema.shape, async (p) => { try { const v = CreateTemplatePartSchema.parse(p); const t = await client.post<Record<string, unknown>>("template-parts", v); return mcpSuccess({ id: t["id"], message: "Template part created" }); } catch(e) { return mcpError(e, "wp_create_template_part"); } });
  server.tool("wp_update_template_part", "Update a template part.", UpdateTemplatePartSchema.shape, async (p) => { try { const { id, ...d } = UpdateTemplatePartSchema.parse(p); await client.put(`template-parts/${id}`, d); return mcpSuccess({ message: "Template part updated" }); } catch(e) { return mcpError(e, "wp_update_template_part"); } });
  server.tool("wp_delete_template_part", "Delete a template part.", DeleteTemplatePartSchema.shape, async (p) => { try { const { id, force } = DeleteTemplatePartSchema.parse(p); await client.del(`template-parts/${id}`, { force }); return mcpSuccess({ message: "Template part deleted" }); } catch(e) { return mcpError(e, "wp_delete_template_part"); } });
  // Navigation — full CRUD
  server.tool("wp_list_navigations", "List navigation block posts.", ListNavigationsSchema.shape, async (p) => { try { const { page, per_page, ...f } = ListNavigationsSchema.parse(p); return mcpSuccess(await client.list("navigation", f as Record<string, string | number | boolean | undefined>, page, per_page)); } catch(e) { return mcpError(e, "wp_list_navigations"); } });
  server.tool("wp_get_navigation", "Get a navigation by ID.", GetNavigationSchema.shape, async (p) => { try { return mcpSuccess(await client.get(`navigation/${GetNavigationSchema.parse(p).id}`)); } catch(e) { return mcpError(e, "wp_get_navigation"); } });
  server.tool("wp_create_navigation", "Create a navigation block.", CreateNavigationSchema.shape, async (p) => { try { const v = CreateNavigationSchema.parse(p); const n = await client.post<Record<string, unknown>>("navigation", v); return mcpSuccess({ id: n["id"], message: "Navigation created" }); } catch(e) { return mcpError(e, "wp_create_navigation"); } });
  server.tool("wp_update_navigation", "Update a navigation block.", UpdateNavigationSchema.shape, async (p) => { try { const { id, ...d } = UpdateNavigationSchema.parse(p); await client.put(`navigation/${id}`, d); return mcpSuccess({ message: `Navigation ${id} updated` }); } catch(e) { return mcpError(e, "wp_update_navigation"); } });
  server.tool("wp_delete_navigation", "Delete a navigation block.", DeleteNavigationSchema.shape, async (p) => { try { const { id, force } = DeleteNavigationSchema.parse(p); await client.del(`navigation/${id}`, { force }); return mcpSuccess({ message: `Navigation ${id} deleted` }); } catch(e) { return mcpError(e, "wp_delete_navigation"); } });
  // Global Styles — with theme styles and variations
  server.tool("wp_get_global_styles", "Get the site's global styles.", GetGlobalStylesSchema.shape, async (p) => { try { return mcpSuccess(await client.get(`global-styles/${GetGlobalStylesSchema.parse(p).id}`)); } catch(e) { return mcpError(e, "wp_get_global_styles"); } });
  server.tool("wp_update_global_styles", "Update global styles (theme.json settings/styles).", UpdateGlobalStylesSchema.shape, async (p) => { try { const { id, ...d } = UpdateGlobalStylesSchema.parse(p); await client.put(`global-styles/${id}`, d); return mcpSuccess({ message: "Global styles updated" }); } catch(e) { return mcpError(e, "wp_update_global_styles"); } });
  server.tool("wp_get_theme_global_styles", "Get a theme's default global styles.", GetThemeGlobalStylesSchema.shape, async (p) => { try { return mcpSuccess(await client.get(`global-styles/themes/${GetThemeGlobalStylesSchema.parse(p).stylesheet}`)); } catch(e) { return mcpError(e, "wp_get_theme_global_styles"); } });
  server.tool("wp_list_global_style_variations", "List style variations for a theme.", ListGlobalStyleVariationsSchema.shape, async (p) => { try { return mcpSuccess(await client.get(`global-styles/themes/${ListGlobalStyleVariationsSchema.parse(p).stylesheet}/variations`)); } catch(e) { return mcpError(e, "wp_list_global_style_variations"); } });
}
