import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { mcpError, mcpSuccess } from "@cmsmcp/shared";
import type { WpClient } from "../api/client.js";
import { ListUsersSchema, GetUserSchema, GetMeSchema, CreateUserSchema, UpdateUserSchema, DeleteUserSchema, ListAppPasswordsSchema, CreateAppPasswordSchema, DeleteAppPasswordSchema } from "../schemas/index.js";

export function registerUserTools(server: McpServer, client: WpClient): void {
  server.tool("wp_list_users", "List WordPress users with role, search filters.", ListUsersSchema.shape, async (p) => { try { const { page, per_page, ...f } = ListUsersSchema.parse(p); return mcpSuccess(await client.list("users", f as Record<string, string | number | boolean | undefined>, page, per_page)); } catch(e) { return mcpError(e, "wp_list_users"); } });
  server.tool("wp_get_user", "Get a user by ID.", GetUserSchema.shape, async (p) => { try { return mcpSuccess(await client.get(`users/${GetUserSchema.parse(p).id}`, { context: "edit" })); } catch(e) { return mcpError(e, "wp_get_user"); } });
  server.tool("wp_get_me", "Get the currently authenticated user's profile.", GetMeSchema.shape, async () => { try { return mcpSuccess(await client.get("users/me", { context: "edit" })); } catch(e) { return mcpError(e, "wp_get_me"); } });
  server.tool("wp_create_user", "Create a new WordPress user with username, email, password, and roles.", CreateUserSchema.shape, async (p) => { try { const v = CreateUserSchema.parse(p); const u = await client.post<Record<string, unknown>>("users", v); return mcpSuccess({ id: u["id"], username: u["username"], email: u["email"], message: `User '${u["username"]}' created` }); } catch(e) { return mcpError(e, "wp_create_user"); } });
  server.tool("wp_update_user", "Update a user's profile, email, roles, or password.", UpdateUserSchema.shape, async (p) => { try { const { id, ...d } = UpdateUserSchema.parse(p); await client.put(`users/${id}`, d); return mcpSuccess({ message: `User ${id} updated` }); } catch(e) { return mcpError(e, "wp_update_user"); } });
  server.tool("wp_delete_user", "Delete a user. Must reassign their content to another user.", DeleteUserSchema.shape, async (p) => { try { const { id, reassign } = DeleteUserSchema.parse(p); await client.del(`users/${id}`, { force: true, reassign }); return mcpSuccess({ message: `User ${id} deleted, content reassigned to ${reassign}` }); } catch(e) { return mcpError(e, "wp_delete_user"); } });
  // Application Passwords
  server.tool("wp_list_app_passwords", "List application passwords for a user.", ListAppPasswordsSchema.shape, async (p) => { try { return mcpSuccess(await client.get(`users/${ListAppPasswordsSchema.parse(p).user_id}/application-passwords`)); } catch(e) { return mcpError(e, "wp_list_app_passwords"); } });
  server.tool("wp_create_app_password", "Create a new application password for a user.", CreateAppPasswordSchema.shape, async (p) => { try { const { user_id, name } = CreateAppPasswordSchema.parse(p); const r = await client.post<Record<string, unknown>>(`users/${user_id}/application-passwords`, { name }); return mcpSuccess({ password: r["password"], uuid: (r as Record<string, unknown>)["uuid"], message: `App password '${name}' created. Save the password now — it won't be shown again.` }); } catch(e) { return mcpError(e, "wp_create_app_password"); } });
  server.tool("wp_delete_app_password", "Delete an application password.", DeleteAppPasswordSchema.shape, async (p) => { try { const { user_id, uuid } = DeleteAppPasswordSchema.parse(p); await client.del(`users/${user_id}/application-passwords/${uuid}`); return mcpSuccess({ message: "App password deleted" }); } catch(e) { return mcpError(e, "wp_delete_app_password"); } });
}
